### Criar cliente (POST)
POST http://localhost/DVL_ATV/api_noite.php
Content-Type: application/json

{
    "nome": "Maria Silva",
    "email": "maria.silv0a@example.com",
    "senha": "Senha@123",
    "telefone": "11987654321",
    "endereco": "Rua das Flores, 456",
    "estado": "RJ",
    "data_nascimento": "1995-05-10"
}

### Deletar cliente (DELETE)
DELETE http://localhost/DVL_ATV/api_noite.php?uuid=COLE-O-UUID-AQUI
